export const ENVIAR_CORREO = "ENVIAR_CORREO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const DETALLE_UN_PRODUCTO = "DETALLE_UN_PRODUCTO";
export const ADD_PRODUCTOS = "ADD_PRODUCTOS";
export const ADD_PRODUCTO = "ADD_PRODUCTO";
export const LIMPIAR_PRODUCTO_DETALLE = "LIMPIAR_DETALLE";
export const ADD_BIBLIOTECA = "ADD_BIBLIOTECA";
export const LIMPIAR_DETALLE_CARRITO = "LIMPIAR_DETALLE_CARRITO";
